"""Story 3.3 SAS replication tests.

The in-session proof: the pure-arithmetic mirror (the exact logic the
generated .sas encodes) must match the real library scoring path to <0.5 on
10+ real applicants - library-independent evidence that the ported arithmetic
is correct. The SAS-side execution itself is the user's OnDemand run.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from scorecard.config import ARTIFACTS_DIR, ACCEPTED_PARQUET

ARTIFACTS_PRESENT = (
    (ARTIFACTS_DIR / "champion_model.joblib").exists() and ACCEPTED_PARQUET.exists()
)

pytestmark = pytest.mark.skipif(
    not ARTIFACTS_PRESENT, reason="champion artifact / raw parquet not present"
)


@pytest.fixture(scope="module")
def bundle():
    import joblib

    return joblib.load(ARTIFACTS_DIR / "champion_model.joblib")


@pytest.fixture(scope="module")
def spec(bundle):
    from sas.export_scorecard import extract_scorecard

    return extract_scorecard(bundle)


@pytest.fixture(scope="module")
def reference(bundle):
    from sas.export_scorecard import build_reference_applicants

    return build_reference_applicants(bundle=bundle)


def test_extraction_matches_artifact(bundle, spec):
    # Coefficients/intercept must be the artifact's exact values (AD-1: no
    # hand-copy drift), and every model variable must have a lookup.
    assert spec["intercept"] == pytest.approx(float(bundle["model"].intercept_[0]))
    for var, coef in zip(bundle["binners"], bundle["model"].coef_.ravel()):
        assert spec["coefficients"][var] == pytest.approx(float(coef))
        assert var in spec["variables"]
    assert spec["pdo"] == 20.0 and spec["base_score"] == 600.0 and spec["base_odds"] == 50.0


def test_mirror_matches_library_scoring_on_reference_applicants(spec, reference):
    """AC #1's arithmetic proof: pure-arithmetic mirror vs the real
    transform_woe+decision_function path, 10+ applicants, <0.5 (in practice
    ~1e-9; 0.5 is the FR17 gate)."""
    from sas.export_scorecard import mirror_score

    assert len(reference) >= 10
    for _, row in reference.iterrows():
        applicant = row.drop(["id", "python_score"]).to_dict()
        mirrored = mirror_score(spec, applicant)
        assert abs(mirrored - row["python_score"]) < 0.5
        assert abs(mirrored - row["python_score"]) < 1e-6  # true fidelity


def test_reference_includes_missing_value_case(reference):
    # The tie-out must exercise the Missing-WOE path, not just clean rows.
    feature_cols = [c for c in reference.columns if c not in ("id", "python_score")]
    assert reference[feature_cols].isna().any().any()


def test_mirror_missing_and_unseen_conventions(spec):
    """Missing -> Missing-bin WOE; unseen category -> Special-bin WOE
    (measured transform_woe behavior, replicated by mirror and .sas)."""
    from sas.export_scorecard import _lookup_woe

    ho = spec["variables"]["home_ownership"]
    assert _lookup_woe(ho, None) == ho["missing_woe"]
    assert _lookup_woe(ho, "NEVER_SEEN_CATEGORY") == ho["special_woe"]
    dti = spec["variables"]["dti"]
    assert _lookup_woe(dti, float("nan")) == dti["missing_woe"]
    # boundary: exactly at a split belongs to the RIGHT bin (left-closed)
    first_split = dti["splits"][0]
    assert _lookup_woe(dti, first_split) == dti["woes"][1]
    assert _lookup_woe(dti, first_split - 1e-9) == dti["woes"][0]


def test_generated_sas_is_self_contained(spec, reference):
    from sas.export_scorecard import generate_sas

    sas = generate_sas(spec, reference)
    assert "datalines;" in sas and "proc print" in sas.lower()
    assert "AUTOGENERATED" in sas
    # every model variable gets a WOE block, and constants are embedded
    for var in spec["coefficients"]:
        assert f"woe_{var}" in sas
    factor = spec["pdo"] / np.log(2)
    assert f"{factor:.10f}" in sas
    # one dataline per reference applicant
    body = sas.split("datalines;")[1].split(";")[0]
    assert len([l for l in body.strip().splitlines() if l.strip()]) == len(reference)


def test_write_outputs_roundtrip(tmp_path):
    from sas.export_scorecard import write_outputs

    sas_path, csv_path = write_outputs(out_dir=tmp_path)
    assert sas_path.exists() and csv_path.exists()
    ref = pd.read_csv(csv_path)
    assert len(ref) >= 10 and "python_score" in ref.columns
