/* ===========================================================================
   scorecard_scoring.sas - champion scorecard ported to SAS (Story 3.3, FR17)
   AUTOGENERATED from champion-1.0.0 artifact - do not hand-edit.
   Regenerate: python -m sas.export_scorecard
   Run as-is in SAS OnDemand: scores 12 embedded reference
   applicants and prints the diff vs the Python ground truth (pass = every
   |diff| < 0.5).
   =========================================================================== */

data reference;
  infile datalines dsd dlm=' ' truncover;
  length id $24 home_ownership $20 purpose $40;
  input id $ fico_range_low annual_inc dti revol_util inq_last_6mths
        home_ownership $ purpose $ python_score;
datalines;
68407277 675.000000 55000.000000 5.910000 29.700000 1.000000 MORTGAGE debt_consolidation 544.990545
68355089 715.000000 65000.000000 16.060000 19.200000 4.000000 MORTGAGE small_business 540.025151
68426831 690.000000 34000.000000 10.200000 68.400000 0.000000 RENT debt_consolidation 537.422646
68476668 680.000000 180000.000000 14.670000 84.500000 0.000000 MORTGAGE debt_consolidation 558.078851
67275481 705.000000 85000.000000 17.610000 5.700000 0.000000 MORTGAGE major_purchase 569.875670
68466926 685.000000 85000.000000 13.070000 34.500000 1.000000 RENT credit_card 550.976750
68525388 670.000000 50000.000000 25.580000 . 0.000000 OWN home_improvement 539.400027
68384400 720.000000 370000.000000 7.090000 . 1.000000 MORTGAGE debt_consolidation 569.149625
68583124 675.000000 44800.000000 21.060000 . 0.000000 MORTGAGE debt_consolidation 538.625201
68616873 700.000000 42000.000000 34.800000 39.100000 0.000000 MORTGAGE credit_card 549.078014
68338832 700.000000 64000.000000 34.950000 67.200000 0.000000 MORTGAGE other 538.428585
68466961 720.000000 92000.000000 21.600000 64.500000 0.000000 MORTGAGE debt_consolidation 563.583874
;
run;

data scored;
  set reference;

  /* --- fico_range_low --- */
  if missing(fico_range_low) then woe_fico_range_low = 0.0000000000;
  else if fico_range_low < 662.5000000000 then woe_fico_range_low = -0.4374026786;
  else if fico_range_low < 667.5000000000 then woe_fico_range_low = -0.3572883479;
  else if fico_range_low < 672.5000000000 then woe_fico_range_low = -0.3250581377;
  else if fico_range_low < 682.5000000000 then woe_fico_range_low = -0.1960055327;
  else if fico_range_low < 687.5000000000 then woe_fico_range_low = -0.1221538547;
  else if fico_range_low < 692.5000000000 then woe_fico_range_low = -0.0434079228;
  else if fico_range_low < 697.5000000000 then woe_fico_range_low = -0.0112078390;
  else if fico_range_low < 702.5000000000 then woe_fico_range_low = 0.1532624530;
  else if fico_range_low < 712.5000000000 then woe_fico_range_low = 0.2051096369;
  else if fico_range_low < 727.5000000000 then woe_fico_range_low = 0.3854459502;
  else if fico_range_low < 757.5000000000 then woe_fico_range_low = 0.6246607982;
  else woe_fico_range_low = 1.1041227955;

  /* --- annual_inc --- */
  if missing(annual_inc) then woe_annual_inc = 0.0000000000;
  else if annual_inc < 28519.0000000000 then woe_annual_inc = -0.5063270210;
  else if annual_inc < 35801.1503906250 then woe_annual_inc = -0.3842726879;
  else if annual_inc < 40405.0000000000 then woe_annual_inc = -0.2877534391;
  else if annual_inc < 49288.5000000000 then woe_annual_inc = -0.1859049056;
  else if annual_inc < 55297.5000000000 then woe_annual_inc = -0.0441119345;
  else if annual_inc < 61566.5000000000 then woe_annual_inc = -0.0110642530;
  else if annual_inc < 65606.0000000000 then woe_annual_inc = 0.0585666330;
  else if annual_inc < 70129.5000000000 then woe_annual_inc = 0.1302949336;
  else if annual_inc < 75002.3984375000 then woe_annual_inc = 0.1525797110;
  else if annual_inc < 86570.5000000000 then woe_annual_inc = 0.2859593947;
  else if annual_inc < 95240.5000000000 then woe_annual_inc = 0.3672310159;
  else if annual_inc < 111327.0000000000 then woe_annual_inc = 0.4730156937;
  else woe_annual_inc = 0.5267764526;

  /* --- dti --- */
  if missing(dti) then woe_dti = 0.0000000000;
  else if dti < 7.8150000572 then woe_dti = 0.3059342782;
  else if dti < 9.3050003052 then woe_dti = 0.2527557975;
  else if dti < 10.8949999809 then woe_dti = 0.2101777819;
  else if dti < 13.2150001526 then woe_dti = 0.1693721734;
  else if dti < 14.8649997711 then woe_dti = 0.1148086103;
  else if dti < 16.7149991989 then woe_dti = 0.0358789095;
  else if dti < 18.2349996567 then woe_dti = -0.0124013465;
  else if dti < 20.7349996567 then woe_dti = -0.0742597089;
  else if dti < 22.9749994278 then woe_dti = -0.1476268078;
  else if dti < 25.8049993515 then woe_dti = -0.1930703789;
  else if dti < 29.1750001907 then woe_dti = -0.2906116285;
  else woe_dti = -0.3502930723;

  /* --- home_ownership --- */
  if missing(home_ownership) then woe_home_ownership = 0.0000000000;
  else if home_ownership in ('MORTGAGE') then woe_home_ownership = 0.2042373682;
  else if home_ownership in ('OWN') then woe_home_ownership = -0.0659570069;
  else if home_ownership in ('NONE', 'OTHER', 'RENT') then woe_home_ownership = -0.1834679094;
  else woe_home_ownership = 0.0000000000; /* unseen category -> Special bin (transform_woe parity) */

  /* --- revol_util --- */
  if missing(revol_util) then woe_revol_util = 0.0304170460;
  else if revol_util < 20.0500001907 then woe_revol_util = 0.4541739023;
  else if revol_util < 33.0499992371 then woe_revol_util = 0.2294599063;
  else if revol_util < 47.0499992371 then woe_revol_util = 0.0903462708;
  else if revol_util < 62.2500000000 then woe_revol_util = 0.0199327396;
  else if revol_util < 67.0499992371 then woe_revol_util = -0.0234687668;
  else if revol_util < 76.6499977112 then woe_revol_util = -0.0994630868;
  else if revol_util < 85.7500000000 then woe_revol_util = -0.1264114500;
  else if revol_util < 91.4500007629 then woe_revol_util = -0.2348602657;
  else woe_revol_util = -0.2699169937;

  /* --- inq_last_6mths --- */
  if missing(inq_last_6mths) then woe_inq_last_6mths = 0.0000000000;
  else if inq_last_6mths < 0.5000000000 then woe_inq_last_6mths = 0.1522951896;
  else if inq_last_6mths < 1.5000000000 then woe_inq_last_6mths = -0.0527385729;
  else if inq_last_6mths < 2.5000000000 then woe_inq_last_6mths = -0.2363675076;
  else woe_inq_last_6mths = -0.3195946785;

  /* --- purpose --- */
  if missing(purpose) then woe_purpose = 0.0000000000;
  else if purpose in ('car', 'credit_card', 'major_purchase') then woe_purpose = 0.1871771742;
  else if purpose in ('home_improvement') then woe_purpose = 0.1554553076;
  else if purpose in ('debt_consolidation', 'house', 'wedding') then woe_purpose = -0.0333040201;
  else if purpose in ('medical', 'moving', 'other', 'renewable_energy', 'small_business', 'vacation') then woe_purpose = -0.3691343459;
  else woe_purpose = 0.0000000000; /* unseen category -> Special bin (transform_woe parity) */

  /* logistic scorecard: logit(bad) then Siddiqi PDO scaling */
  logit = -1.9284226514 +
    (-0.7686124877) * woe_fico_range_low +
    (-0.7837917413) * woe_annual_inc +
    (-0.6119268786) * woe_dti +
    (-0.4776616581) * woe_home_ownership +
    (-0.2867651105) * woe_revol_util +
    (-1.0981358602) * woe_inq_last_6mths +
    (-0.9100389248) * woe_purpose;
  factor = 28.8539008178;
  offset = 487.1228762045;
  sas_score = offset + factor * (-logit);

  diff = sas_score - python_score;
  abs_diff = abs(diff);
  pass = (abs_diff < 0.5);
run;

title "SAS vs Python scorecard tie-out (pass = every abs_diff < 0.5)";
proc print data=scored noobs;
  var id sas_score python_score diff abs_diff pass;
  format sas_score python_score 12.4 diff abs_diff 12.6;
run;

proc means data=scored max n;
  var abs_diff;
run;
